//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCoustomer
    {
        public int cId { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int uId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
